### ISSUE TITLE
Gateway header is missing

### ISSUE THREAD

**Issue by dplewis** [hps/heartland-ios#18]
This error was thrown when i used `transaction.chargeAmount = 17.03f;`;

Upon further inspection I found this.

```
Unable to process request.  Message failed validation.  The 'http://Hps.Exchange.PosGateway:Amt' element is invalid - The value '17.030001' is invalid according to its datatype 'http://Hps.Exchange.PosGateway:amtType' - The FractionDigits constraint failed.  (line#1,pos#1263)
```

The fix was to use a double (17.03) instead of float (17.03f).

Floats are used in your test cases as well

https://github.com/hps/heartland-ios/blob/master/Example/Tests/Heartland_GatewayTests.m#L50

**Expected Results**
Request to be successful or proper error message

**Actual Results**
Request failed

**Comment by dplewis** [comment]
I'm using a Node backend so this issue doesn't apply to me anymore.

It might be helpful to fix for newer users

**Comment by slogsdon** [comment]
Thanks for the note, @dplewis! We'll take a look on our end to get this handled correctly.

**Comment by dplewis** [comment]
Closing via https://github.com/hps/heartland-ios/commit/9c61c93bf9d8234d288ebe6b1727f997c38e3122
