### ISSUE TITLE
Unable to build the app 

### ISSUE THREAD

**Issue by avinas-incent** [hps/heartland-ios#35]
Hi,

I'm using pod 'Heartland-iOS-SDK' in my objective c Xcode project. when I'm trying to build the project it says  'GlobalMobileSDK/GlobalMobileSDK.h' file not found so I'm unable to build the project cuz of this issue along with this could not build the Objective-C module 'Heartland_iOS_SDK' is there any solution for this? 

Tried several ways to resolve this no use. Please provide a solution for this.

**Comment by macfanatic** [comment]
Did you make any progress on this issue? We are still seeing this upgrading from 1.3 to 2.0 in an existing integration and immediately fails.
