### ISSUE TITLE
Arm64 build target missing?

### ISSUE THREAD

**Issue by c-fitzmaurice** [hps/heartland-ios#67]
Hello, I'm trying to integrate your SDK into an Expo Native Module but am getting a build error: `target 'arm64-apple-ios-simulator'` not found -- can you provide me some direction here, please?

I think it's related to these lines here: https://github.com/hps/heartland-ios/blob/44f5e887f0a2da2bdf703a0627086105ccfe27a3/Heartland-iOS-SDK.podspec#L40-L45

Note: I'm on an M1 Mac

<img width="739" alt="Screenshot 2023-07-12 at 12 53 07 AM" src="https://github.com/hps/heartland-ios/assets/3401771/394ffedd-c02e-4872-8848-e83f73375b29">

**Comment by c-fitzmaurice** [comment]
I'm also getting this build error:

```
RUN_FASTLANE] › Compiling heartland Pods/Heartland-iOS-SDK » HpsTerminalUtilities.m
[RUN_FASTLANE] 
❌  (ios/Pods/Heartland-iOS-SDK/Heartland-iOS-SDK/Classes/Terminals/HpsTerminalResponse.m:3:9)

  1 | #import "HpsTerminalResponse.h"
  2 | #import "HpsHpaSharedParams.h"
> 3 | #import <Heartland_iOS_SDK/Heartland_iOS_SDK-Swift.h>
    |         ^ 'Heartland_iOS_SDK/Heartland_iOS_SDK-Swift.h' file not found
  4 | 
  5 | @implementation HpsTerminalResponse
  6 | 
```

**Comment by felixhps** [comment]
Hi,

Unfortunately I don't have experience with Expo, but are you able to run the project in Xcode? If so, what version of Xcode are you using, and are you on an Intel or Apple Silicon mac?

Thanks
Felix
